name: RJC
title: Ryan J. Chen's Website
description: RJC's personal website
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: ryanjaychen@gmail.com
# See: https://disqus.com/
disqus_username: ##
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
